name: Auto Move Issues in Project

on:
  issues:
    types: [opened, assigned]

jobs:
  move_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Move newly created issues to Backlog
        if: github.event.action == 'opened'
        run: |
          gh project item-add 3 --owner VoNgocHoangLanUIT --url "${{ github.event.issue.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Move assigned issues to In Progress
        if: github.event.action == 'assigned'
        run: |
          ISSUE_ID=$(gh project item-list 3 --user VoNgocHoangLanUIT --format json | jq -r '.items[] | select(.content.title=="${{ github.event.issue.title }}") | .id')
          gh project item-update 3 --user VoNgocHoangLanUIT --id "$ISSUE_ID" --field "Status=In Progress"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
